---
title: "vignette_details"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Toolkit for estimation of hierarchical Bayesian VARs. Implements prior selection 
for conjugate priors in the fashion of Giannone et al. (2015)  that accounts for 
uncertainty about prior hyperparameters. Allows for the  computation of impulse 
responses as well as forecasts based on draws of  coefficients from their 
respective posterior distribution.

The main function to perform hierarchical Bayesian VAR estimation is 
`bvar()` with settings regarding the lag length, number of iterations 
to be used and so on. 

Via the helper function `bv_priors()` settings regarding the priors
implemented can be adjusted e.g. which priors to model hierarchically or in 
which range the hyperparameter values of those priors are allowed to vary. It
utilizes other helper functions (see `bv_mn()`, `bv_dummy()`) to set up the 
Minnesota prior or other conjugate priors via dummy observations.

The helper function `bv_mh()` provides settings regarding the 
Metropolis-Hastings step. It can for example be adjusted to use other scalings 
for the Hessian that determines the range of the hyperparameters or to keep the
acceptance rate of the Metropolis-Hastings step between a certain range.

To set options regarding the computation of impulse responses or forecasts the
helper functions `bv_irf()` and `bv_fcast()` are to be 
utilized. Adjustments to the horizon for which they are respectively computed 
can be set as well as the type of identifcation of shocks for the impulse 
responses. Currently only unconditional forecasts are implemented, however 
conditional ones will follow in the near future. 
